use_frameworks!

target 'UURCCentralizedTokenView_Example' do
  pod 'UURCCentralizedTokenView', :path => '../'
  pod 'Masonry', '1.0.0'

  target 'UURCCentralizedTokenView_Tests' do
    pod 'UURCCentralizedTokenView', :path => '../'
  end
end
